# Generated by Django 3.1.7 on 2021-02-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pan_image',
            field=models.ImageField(blank=True, upload_to='user'),
        ),
    ]
